-- ═════════════════════════════════════════════════════════════════════════════════════════
-- CIudades para Supabase - Total: 246 ciudades
-- Copia este código y ejecútalo en el SQL Editor de Supabase
-- ═════════════════════════════════════════════════════════════════════════════════════════

DELETE FROM cities;

INSERT INTO cities (name, province, zone_name, city_tier, delivery_time, is_active) VALUES
('CUENCA', 'AZUAY', 'nacional', 'principal', '24 HORAS', true),
('BELLAVISTA', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('CAÑARIBAMBA', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('EL BATÁN', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('EL SAGRARIO', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('EL VECINO', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('GIL RAMÍREZ DÁVALOS', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('HUAYNACÁPAC', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('MACHÁNGARA', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('MONAY', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('SAN BLAS', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('SAN SEBASTIÁN', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('SUCRE', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('TOTORACOCHA', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('YANUNCAY', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('HERMANO MIGUEL', 'AZUAY', 'nacional', 'secundaria', '24 HORAS', true),
('CAPULISPAMBA', 'AZUAY', 'nacional', 'secundaria', '48 HORAS', true),
('BAÑOS', 'AZUAY', 'nacional', 'secundaria', '48 HORAS', true),
('RICAURTE', 'AZUAY', 'nacional', 'secundaria', '48 HORAS', true),
('SAN JOAQUIN', 'AZUAY', 'nacional', 'secundaria', '48 HORAS', true),
('SAYAUSI', 'AZUAY', 'nacional', 'secundaria', '48 HORAS', true),
('TURI', 'AZUAY', 'nacional', 'secundaria', '48 HORAS', true),
('SININCAY (RACAR)', 'AZUAY', 'nacional', 'secundaria', '48 HORAS', true),
('LUIS CORDERO', 'AZUAY', 'nacional', 'especial', '48 A 72 HORAS', true),
('SANTA ANA', 'AZUAY', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('TARQUI', 'AZUAY', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('VALLE', 'AZUAY', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('GIRON', 'AZUAY', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('GUALACEO', 'AZUAY', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('TULCÁN', 'CARCHI', 'norte', 'principal', '24 HORAS', true),
('GONZÁLEZ SUÁREZ', 'CARCHI', 'nacional', 'secundaria', '24 HORAS', true),
('BOLIVAR', 'CARCHI', 'nacional', 'especial', '24 HORAS', true),
('HUACA', 'CARCHI', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('SAN GABRIEL', 'CARCHI', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('JULIO ANDRADE', 'CARCHI', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('MIRA', 'CARCHI', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('AZOGUES', 'CAÑAR', 'nacional', 'especial', '48 HORAS', true),
('CAÑAR', 'CAÑAR', 'nacional', 'secundaria', '48 HORAS', true),
('EL TAMBO', 'CAÑAR', 'nacional', 'secundaria', '72 HORAS', true),
('BIBLIAN', 'CAÑAR', 'nacional', 'secundaria', '72 HORAS', true),
('LATACUNGA', 'COTOPAXI', 'nacional', 'principal', '24 HORAS', true),
('ELOY ALFARO  (SAN FELIPE)', 'COTOPAXI', 'nacional', 'secundaria', '24 HORAS', true),
('IGNACIO FLORES (PARQUE FLORES)', 'COTOPAXI', 'nacional', 'secundaria', '24 HORAS', true),
('JUAN MONTALVO (SAN SEBASTIÁN)', 'COTOPAXI', 'nacional', 'secundaria', '24 HORAS', true),
('LA MATRIZ', 'COTOPAXI', 'nacional', 'secundaria', '24 HORAS', true),
('SAN BUENAVENTURA', 'COTOPAXI', 'nacional', 'secundaria', '24 HORAS', true),
('MULALO (LASSO)', 'COTOPAXI', 'nacional', 'especial', 'LUNES', true),
('SALCEDO', 'COTOPAXI', 'nacional', 'secundaria', '72 HORAS', true),
('PUJILI', 'COTOPAXI', 'nacional', 'secundaria', 'MARTES', true),
('SAQUISILI', 'COTOPAXI', 'nacional', 'secundaria', 'LUNES', true),
('RIOBAMBA', 'CHIMBORAZO', 'nacional', 'principal', '24 HORAS', true),
('LIZARZABURU', 'CHIMBORAZO', 'nacional', 'secundaria', '24 HORAS', true),
('MALDONADO', 'CHIMBORAZO', 'nacional', 'secundaria', '24 HORAS', true),
('VELASCO', 'CHIMBORAZO', 'nacional', 'secundaria', '24 HORAS', true),
('VELOZ', 'CHIMBORAZO', 'nacional', 'secundaria', '24 HORAS', true),
('YARUQUÍES', 'CHIMBORAZO', 'nacional', 'secundaria', '24 HORAS', true),
('GUANO RETIRO DE OFICINA RIOBAMBA', 'CHIMBORAZO', 'nacional', 'secundaria', 'RETIRO OFICINA RIOBAMBA', true),
('GUAYAQUIL', 'GUAYAS', 'nacional', 'principal', '24 HORAS', true),
('AYACUCHO', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('BOLÍVAR  (SAGRARIO)', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('CARBO (CONCEPCIÓN)', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('FEBRES CORDERO', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('GARCÍA MORENO', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('LETAMENDI', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('NUEVE DE OCTUBRE', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('OLMEDO  (SAN ALEJO)', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('ROCA', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('ROCAFUERTE', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('SUCRE', 'GUAYAS', 'nacional', 'secundaria', '24 HORAS', true),
('TARQUI', 'GUAYAS', 'nacional', 'secundaria', '48 HORAS', true),
('URDANETA', 'GUAYAS', 'nacional', 'secundaria', '48 HORAS', true),
('XIMENA', 'GUAYAS', 'nacional', 'secundaria', '48 HORAS', true),
('DURAN', 'GUAYAS', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('EL RECREO', 'GUAYAS', 'nacional', 'especial', '48 A 72 HORAS', true),
('ELOY ALFARO (DURÁN)', 'GUAYAS', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('PASCUALES', 'GUAYAS', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('LA PUNTILLA (SATÉLITE)', 'GUAYAS', 'nacional', 'secundaria', '48 A 72 HORAS', true),
('SAMBORONDÓN', 'GUAYAS', 'nacional', 'secundaria', '48 HORAS', true),
('LA AURORA (SATÉLITE)', 'GUAYAS', 'nacional', 'secundaria', 'MIERCOLES', true),
('LAUREL', 'GUAYAS', 'nacional', 'secundaria', 'MIERCOLES', true),
('LIMONAL', 'GUAYAS', 'nacional', 'secundaria', 'MIERCOLES', true),
('SAN CARLOS', 'GUAYAS', 'nacional', 'secundaria', '72 HORAS', true),
('IBARRA', 'IMBABURA', 'norte', 'principal', '24 HORAS', true),
('ATUNTAQUI', 'IMBABURA', 'norte', 'secundaria', '24 HORAS', true),
('OTAVALO', 'IMBABURA', 'norte', 'secundaria', '24 HORAS', true),
('COTACACHI', 'IMBABURA', 'norte', 'especial', 'MARTES Y JUEVES', true),
('SAN ANTONIO', 'IMBABURA', 'nacional', 'secundaria', '24 HORAS', true),
('ANTONIO ANTE', 'IMBABURA', 'nacional', 'especial', '48 HORAS', true),
('ANDRADE MARÍN  (LOURDES)', 'IMBABURA', 'nacional', 'secundaria', '48 HORAS', true),
('SAN JOSE DE CHALTURA', 'IMBABURA', 'nacional', 'secundaria', '48 HORAS', true),
('QUEVEDO', 'LOS RIOS', 'nacional', 'principal', '24 HORAS', true),
('BUENA FE', 'LOS RIOS', 'nacional', 'secundaria', '24 HORAS', true),
('SAN CAMILO', 'LOS RIOS', 'nacional', 'secundaria', '24 HORAS', true),
('VALENCIA', 'LOS RIOS', 'nacional', 'secundaria', '24 HORAS', true),
('LA MANA', 'LOS RIOS', 'nacional', 'secundaria', '24 HORAS', true),
('EL EMPALME', 'LOS RIOS', 'nacional', 'especial', 'MARTES - JUEVES - SABADO', true),
('SAN JUAN', 'LOS RIOS', 'nacional', 'secundaria', 'MARTES - JUEVES - SABADO', true),
('TRES POSTES', 'LOS RIOS', 'nacional', 'secundaria', 'MARTES - JUEVES - SABADO', true),
('BABAHOYO', 'LOS RIOS', 'nacional', 'secundaria', 'MARTES - JUEVES - SABADO', true),
('VENTANAS', 'LOS RIOS', 'nacional', 'secundaria', 'MARTES - JUEVES - SABADO', true),
('JUJAN', 'LOS RIOS', 'nacional', 'secundaria', 'MARTES - JUEVES - SABADO', true),
('MILAGRO', 'LOS RIOS', 'nacional', 'secundaria', 'MARTES - JUEVES - SABADO', true),
('MANTA', 'MANABI', 'nacional', 'principal', '24 HORAS - DESPUES DE 13:00 PM', true),
('PORTOVIEJO', 'MANABI', 'nacional', 'principal', '24 HORAS', true),
('TOSAGUA', 'MANABI', 'nacional', 'secundaria', '24 HORAS', true),
('FLAVIO ALFARO', 'MANABI', 'nacional', 'secundaria', '24 HORAS', true),
('ROCAFUERTE', 'MANABI', 'nacional', 'secundaria', '24 HORAS', true),
('PICOAZA', 'MANABI', 'nacional', 'secundaria', '24 HORAS', true),
('MONTECRISTI', 'MANABI', 'nacional', 'secundaria', '24 HORAS', true),
('CHONE', 'MANABI', 'nacional', 'secundaria', '24 HORAS', true),
('EL CARMEN', 'MANABI', 'nacional', 'secundaria', '24 HORAS', true),
('BAHIA', 'MANABI', 'nacional', 'especial', 'VIERNES', true),
('CALCETA', 'MANABI', 'nacional', 'secundaria', 'MIERCOLES - SABADO', true),
('QUITO', 'PICHINCHA', 'norte', 'principal', '24 HORAS', true),
('BELISARIO QUEVEDO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('CARCELÉN', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('CENTRO HISTÓRICO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('CHILIBULO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('CHILLOGALLO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('CHIMBACALLE', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('COCHAPAMBA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('COMITÉ DEL PUEBLO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('COTOCOLLAO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('EL CONDADO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('IÑAQUITO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('ITCHIMBIA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('JIPIJAPA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('KENNEDY', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA ARGELIA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA CONCEPCIÓN', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA FERROVIARIA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA LIBERTAD', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA MAGDALENA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA MENA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA MERCED (CENTRO HISTORICO)', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('MARISCAL SUCRE', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('PONCEANO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('QUITUMBE', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('RUMIPAMBA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('SAN BARTOLO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('SAN ISIDRO DEL INCA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('SOLANDA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('TURUBAMBA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('SAN JUAN', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('CALDERON (CARAPUNGO)', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('CONOCOTO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('CUMBAYA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('GUAMANÍ', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA ECUATORIANA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LLANO CHICO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('POMASQUI', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('SAN ANTONIO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('TUMBACO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('ZAMBIZA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('COTOGCHOA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('SAN RAFAEL', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('SANGOLQUÍ', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('AMAGUAÑA', 'PICHINCHA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('TAMBILLO', 'PICHINCHA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('UYUMBICHO', 'PICHINCHA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('TABABELA', 'PICHINCHA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('CAYAMBE', 'PICHINCHA', 'norte', 'principal', '24 HORAS', true),
('TABACUNDO', 'PICHINCHA', 'norte', 'secundaria', '24 HORAS', true),
('ASCAZUBI', 'PICHINCHA', 'nacional', 'especial', '48 HORAS', true),
('SANTA ROSA', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('MACHACHI', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('ALOAG', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('ALOASÍ', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('CUTUGLAHUA', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('CHECA (CHILPA)', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('EL QUINCHE', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('GUANGOPOLO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('GUAYLLABAMBA', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('PIFO', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('PINTAG', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('PUEMBO', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('PUENGASI', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('YARUQUI', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('FAJARDO', 'PICHINCHA', 'nacional', 'secundaria', '48 HORAS', true),
('SAN PEDRO DE TABOADA', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('NAYON', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('LA MERCED', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('ILALO', 'PICHINCHA', 'nacional', 'secundaria', '24 HORAS', true),
('SANTO DOMINGO', 'SANTO DOMINGO', 'nacional', 'principal', '24 HORAS', true),
('ABRAHAM CALAZACÓN', 'SANTO DOMINGO', 'nacional', 'principal', '24 HORAS', true),
('RÍO TOACHI', 'SANTO DOMINGO', 'nacional', 'principal', '24 HORAS', true),
('RÍO VERDE', 'SANTO DOMINGO', 'nacional', 'principal', '24 HORAS', true),
('ZARACAY', 'SANTO DOMINGO', 'nacional', 'principal', '24 HORAS', true),
('EL CARMEN', 'SANTO DOMINGO', 'nacional', 'principal', 'DE 24 A 48 HORAS', true),
('LA CONCORDIA', 'SANTO DOMINGO', 'nacional', 'principal', 'DE 24 A 48 HORAS', true),
('LA UNION', 'SANTO DOMINGO', 'nacional', 'principal', 'DE 24 A 48 HORAS', true),
('QUININDE', 'SANTO DOMINGO', 'nacional', 'principal', 'DE 24 A 48 HORAS', true),
('PATRICIA PILAR', 'SANTO DOMINGO', 'nacional', 'principal', 'DE 24 A 48 HORAS', true),
('SAN MIGUEL DE LOS BANCOS', 'SANTO DOMINGO', 'nacional', 'principal', '72 HORAS', true),
('PEDRO VICENTE MALDONADO', 'SANTO DOMINGO', 'nacional', 'principal', '72 HORAS', true),
('PUERTO QUITO', 'SANTO DOMINGO', 'nacional', 'principal', '72 HORAS', true),
('ESMERALDAS', 'ESMERALDAS', 'nacional', 'principal', '24 HORAS', true),
('TONSUPA', 'ESMERALDAS', 'nacional', 'principal', '24 HORAS', true),
('ATACAMES', 'ESMERALDAS', 'nacional', 'principal', '24 HORAS', true),
('MUISNE', 'ESMERALDAS', 'nacional', 'principal', '48 HORAS', true),
('PEDERNALES', 'ESMERALDAS', 'nacional', 'principal', 'MIERCOLES - SABADO', true),
('AMBATO', 'TUNGURAHUA', 'nacional', 'principal', '24 HORAS', true),
('ATOCHA – FICOA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 HORAS', true),
('CELIANO MONGE', 'TUNGURAHUA', 'nacional', 'secundaria', '24 HORAS', true),
('HUACHI LORETO', 'TUNGURAHUA', 'nacional', 'secundaria', '24 HORAS', true),
('LA MERCED', 'TUNGURAHUA', 'nacional', 'secundaria', '24 HORAS', true),
('LA PENÍNSULA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 HORAS', true),
('MATRIZ', 'TUNGURAHUA', 'nacional', 'secundaria', '24 HORAS', true),
('SAN FRANCISCO', 'TUNGURAHUA', 'nacional', 'secundaria', '24 HORAS', true),
('SAN BARTOLOME DE PINLLO', 'TUNGURAHUA', 'nacional', 'secundaria', '24 HORAS', true),
('ATAHUALPA (CHISALATA)', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('AUGUSTO N. MARTINEZ (MUNDUGLEO)', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('HUACHI GRANDE', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('PICAIGUA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('SANTA ROSA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('TOTORAS', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('PISHILATA', 'TUNGURAHUA', 'nacional', 'especial', '48 HORAS', true),
('HUACHI CHICO', 'TUNGURAHUA', 'nacional', 'secundaria', '48 HORAS', true),
('CEVALLOS', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('MOCHA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('IZAMBA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('PATATE', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('BAÑOS DE AGUA SANTA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('PELILEO', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('QUERO', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('PELILEO GRANDE', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('SALASACA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('CIUDAD NUEVA', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('PILLARO', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('TISALEO', 'TUNGURAHUA', 'nacional', 'secundaria', '24 A 48 HORAS', true),
('LAGO AGRIO', 'SUCUMBIOS', 'oriente', 'principal', '24 HORAS', true),
('SHUSHUFINDI', 'SUCUMBIOS', 'oriente', 'secundaria', '24 HORAS', true),
('CASCALES', 'SUCUMBIOS', 'oriente', 'especial', '24 A 48 HORAS', true),
('LUMBAQUI', 'SUCUMBIOS', 'oriente', 'secundaria', '24 A 48 HORAS', true),
('EL ENO', 'SUCUMBIOS', 'oriente', 'secundaria', '24 A 48 HORAS', true),
('PROYECTO', 'SUCUMBIOS', 'oriente', 'secundaria', '24 A 48 HORAS', true),
('EL COCA', 'FRANCISCO DE ORELLANA', 'oriente', 'principal', '24 HORAS', true),
('JOYA DE LOS SACHAS', 'FRANCISCO DE ORELLANA', 'oriente', 'secundaria', '24 HORAS', true),
('DAYUMA', 'FRANCISCO DE ORELLANA', 'oriente', 'especial', '24 A 48 HORAS', true),
('LORETO', 'FRANCISCO DE ORELLANA', 'oriente', 'secundaria', '24 A 48 HORAS', true),
('TENA', 'NAPO', 'oriente', 'principal', 'MARTES - JUEVES', true),
('BAEZA', 'NAPO', 'oriente', 'secundaria', 'MARTES - JUEVES', true),
('EL CHACO', 'NAPO', 'oriente', 'especial', 'MARTES - JUEVES', true),
('ARCHIDONA', 'NAPO', 'oriente', 'secundaria', 'MARTES - JUEVES', true),
('PUYO', 'PASTAZA', 'oriente', 'principal', 'MARTES - JUEVES', true),
('SANTA CLARA', 'PASTAZA', 'oriente', 'secundaria', 'MARTES - JUEVES', true);
